name: CI
on:
  push:
    paths:
    - '**.go'
    - 'go.mod'
    - 'go.sum'
    - '.github/workflows/ci.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu
        - windows
        - macos
        go:
        - '1.13'
        - '1.14'
        - '1.15'
        - '1.16'
        - '1.17'
    runs-on: ${{ matrix.os }}-latest
    name: Go ${{ matrix.go }} (${{ matrix.os }})
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Go Cache Directory
      id: go-cache-paths
      run: |
        GOCACHE="$(go env GOCACHE)"
        GOMODCACHE="$(go env GOMODCACHE)"
        test -z "${GOCACHE}" && GOCACHE="${HOME}/.cache/go-build"
        test -z "${GOMODCACHE}" && GOMODCACHE="$(go env GOPATH)/pkg/mod"
        echo "::set-output name=go-build::${GOCACHE}"
        echo "::set-output name=go-mod::${GOMODCACHE}"
    - name: Go Build Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-${{ matrix.go }}-build-${{ hashFiles('**/go.sum') }}
    - name: Go Mod Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-${{ matrix.go }}-mod-${{ hashFiles('**/go.sum') }}
    - name: Go Stringer Tool
      run: go get golang.org/x/tools/cmd/stringer
      env:
        GO111MODULE: off
    - name: Go Mod Download
      run: go mod download
    - name: Go Mod Tidy
      run: go mod tidy
    - name: Go Vet
      run: go vet ./...
    - name: Go Test
      run: go test -v ./...
    - name: Go Lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
        skip-build-cache: true
        skip-pkg-cache: true
    - name: Snapshot
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --config .goreleaser/snapshot.yml --rm-dist --snapshot
